version: '3.8'

services:
  dashboard-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dashboard-app
    image: anoopkarnik/dashboard-app:latest
    ports:
      - "4000:4000"
    networks:
      - turborepo-network

  scheduler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.scheduler
    image: anoopkarnik/scheduler:latest 
    ports:
      - "4001:4001"
    networks:
      - turborepo-network
  
  processor:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.processor
    image: anoopkarnik/processor:latest 
    ports:
      - "4002:4002"
    networks:
      - turborepo-network
  
  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    image: anoopkarnik/worker:latest 
    ports:
      - "4003:4003"
    networks:
      - turborepo-network
      
  flask-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.flask-worker
    image: anoopkarnik/flask-worker:latest 
    ports:
      - "5000:5000"
    networks:
      - turborepo-network
networks:
  turborepo-network:
    driver: bridge