version: '3.8'

services:
  dashboard-app:
    image: anoopkarnik/dashboard-app:latest
    restart: always
    ports:
      - "4000:4000"
    networks:
      - turborepo-network
    env_file:
      - .env.dashboard-app
    volumes:
      - /home/ubuntu/logs/dashboard-app:/app/apps/dashboard-app/logs

  scheduler:
    image: anoopkarnik/scheduler:latest
    restart: always
    ports:
      - "4001:4001"
    networks:
      - turborepo-network
    env_file:
      - .env.scheduler
    volumes:
      - /home/ubuntu/logs/scheduler:/app/apps/scheduler/logs

  processor:
    image: anoopkarnik/processor:latest
    restart: always
    ports:
      - "4002:4002"
    networks:
      - turborepo-network
    env_file:
      - .env.processor
    volumes:
      - /home/ubuntu/logs/processor:/app/apps/processor/logs

  worker:
    image: anoopkarnik/worker:latest
    restart: always
    ports:
      - "4003:4003"
    networks:
      - turborepo-network
    env_file:
      - .env.worker
    volumes:
      - /home/ubuntu/logs/worker:/app/apps/worker/logs
  flask-worker:
    image: anoopkarnik/flask-worker:latest
    restart: always
    ports:
      - "5000:5000"
    networks:
      - turborepo-network
    env_file:
      - .env.flask-worker
    volumes:
      - /home/ubuntu/logs/flask-worker:/app/apps/flask-worker/app/logs
      
networks:
  turborepo-network:
    external: true